---
title: "Ejercicios Tema 5 - Variables aleatorias bidimensionales"
author: "Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir"
date: "Curso de Probabilidad y Variables Aleatorias con R y Python"
output:
  pdf_document:
    toc: yes
    number_sections: yes
  word_document:
    toc: yes
  html_document: 
    toc: yes
    number_sections: yes
    keep_md: yes
linkcolor: red
header-includes: \renewcommand{\contentsname}{Contenidos}
citecolor: blue
toccolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand\momento{m}
\newcommand{\momentocentral}{\mu}
\newcommand{\FunGenMom}{m}
\newcommand{\FunCar}{\phi}

# Variables aleatorias bidimensionales discretas

## Pregunta 1.

Una moneda no trucada tiene un 1 pintado en una cara y un 2
en la otra cara. Se llanza al aire dos veces la moneda. Sea $X$ la suma de los dos números 
obtenidos y sea $Y$ la diferencia de los dos
números (el primero menos el segundo). Hallar la función de probabilidad
conjunta $P_{XY}(x,y)$, la función de probabilidad de $X$, $P_X(x)$ y la función de probabilidad 
de $Y$, $P_Y(y)$.

## Pregunta 2.

Suponemos que se pinta un "+1" en una cara
de una moneda no trucada y un "-1" en la otra cara. La moneda se llanza al aire dos veces. Sea $X$ el número que sale la primera
vez y $Y$ el número que sale la segunda vez. Hallar
$P_{XY}(x,y)$, $E(X)$, $E(Y)$ y $E\left({X\over Y}\right)$.


## Pregunta 3.

 Se llanza 3 veces una moneda no trucada. Sea $X$ el número de caras
que se obtienen e $Y$ el número de cruces. Hallar la función de probabilidad
conjunta para $(X,Y)$ y hallar $\sigma_{XY}=E(XY)-E(X)\cdot E(Y)$.

## Pregunta 4.
 Sean $X$ y $Y$ variables aleatorias discretas con función de probabilidad
conjunta: 
$$
P_{XY}(x,y)=
\left\{\begin{array}{ll}
{1\over n^2}, & \mbox{por $x=1,2,\ldots,n,\quad
y=1,2,\ldots,n$},\\
0, & \mbox{en los otros casos.}
\end{array}\right.
$$
Comprobar que $X$ e $Y$ son independientes.

## Pregunta 5.

 Si la probabilidad conjunta para $(X,Y)$ no se anula en exactamente 3 puntos, ¿qué se tiene que
cumplir para que $X$ y $Y$ sean independientes?

## Pregunta 6.

Sea $(X,Y)$ la variable aleatoria
bidimensional con función de probabilidad conjunta:

$$
\renewcommand{\arraystretch}{1.5}
\begin{tabular}{c|ccc}
$Y\backslash X$&$-1$&$0$&$1$ \\
\hline
$-1$&$\frac{1}{9}$&$\frac{1}{18}$&$\frac{1}{9}$ \\
$0$&$\frac{1}{9}$&$\frac{1}{9}$&$\frac{1}{18}$ \\
$1$&$\frac{2}{9}$&$0$&$\frac{2}{9}$ \\\hline
\end{tabular}
$$
Hallar $E (Y|X=1)$.


# Variables aleatorias bidimensionales continuas

## Pregunta 7.

 ¿Cuál es el valor de $A$ si se quiere que la siguiente función
$$
f_{XY}(x,y)=
\left\{\begin{array}{ll}
A {x\over y}, & \mbox{si $0<x<1$, $1<y<2$}, \\ 0, & \mbox{en los
otros casos,}
\end{array}\right.
$$
sea una función de densidad para la variable aleatoria conjunta $(X,Y)$.

 


## Pregunta 8.

 Suponemos que $(X,Y)$ es una variable aleatoria bidimensional
continua con función de densidad: 
$$
f_{XY}(x,y)=
\left\{\begin{array}{ll}
{1\over x}, & \mbox{si
$0<y<x$, $0<x<1$},\\
0, & \mbox{en los otros casos.}
\end{array}\right.
$$
Hallar las funciones de densidad marginales para $X$ y $Y$.
 

## Pregunta 9.

Suponemos que
$(X,Y)$ tiene  densidad $f_{XY}=c$ para $(x,y)$ en el cuadrilátero de vértices
$(0,0)$, $(1,1)$, $(a,1-a)$ y $(1-a,a)$ donde $0\leq a\leq \frac{1}{2}$.
1. Hallar el valor de $c$.
2.  Hallar $\rho_{XY}$ si $a=0$ y $a=\frac{1}{2}$.

  

## Pregunta 10

Consideramos la función:
$$
f(x,y)=
\left\{\begin{array}{ll}
3x, & \mbox{si $0\leq x\leq 1$ y $x\leq y\leq 1$},\\
3y, & \mbox{si
$0\leq x\leq 1$ y $0\leq y\leq x$},\\ 0, & \mbox{en caso contrario.}
\end{array}\right.
$$
1. Comprobar que es una función de densidad.
2. Hallar la función de distribución.
3. Hallar la función de densidad de $X$, $Y$, $X|Y=y$ y $Y|X=x$.


  

## Pregunta 11

La variable $(X,Y)$ está distribuida uniformemente en el círculo
$x^2+y^2\leq 4$. Calcular:
1. $P(Y>k X)$, para cualquier valor de $k$.
2. Densidad marginal de la variable aleatoria $X$.
3.  Densidad para la variable aleatoria condicionada $X|Y=1$.
4. $P(|X|<1|Y=0.5)$.

  