---
title: "Ejercicios Tema 7 - Ley de los grandes números y Teorema Central del Límite"
author: "Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir"
date: "Curso de Probabilidad y Variables Aleatorias con R y Python"
output:
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  word_document:
    toc: yes
    toc_depth: '4'
linkcolor: red
header-includes: \renewcommand{\contentsname}{Contenidos}
citecolor: blue
toccolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
r=0
```

# Convergencia de variables aleatorias

## Pregunta `r r=r+1; r`.

Demostrar que si la sucesión $\{X_n\}_{n=1}^\infty$ converge hacia $X$ casi seguramente, la sucesión $\{X_n-X\}_{n=1}^\infty$ converge hacia cero casi seguramente.

## Pregunta `r r=r+1; r`.

Demostrar que si la sucesión $\{X_n\}_{n=1}^\infty$ converge hacia $X$ en probabilidad, la sucesión $\{X_n-X\}_{n=1}^\infty$ converge hacia cero en probabilidad.

## Pregunta `r r=r+1; r`.

Sea $\{X_n\}_{n=1}^\infty$ la sucesión de variables aleatorias Bernoulli con parámetro $p_n=\frac{1}{n^2}$. Estudiar la convergencia casi segura, en probabilidad y en ley de la sucesión anterior.

## Pregunta `r r=r+1; r`.

Sea $\{X_n\}_{n=1}^\infty$ la sucesión de variables aleatorias con función de densidad:
$$
f_{X_n}(x)=\begin{cases}
\frac{n x^{n-1}}{\theta^n}, & \mbox{ si }0<x<\theta, \\
0, & \mbox{en caso contrario,}
\end{cases}
$$
donde $\theta$ es un valor real positivo. Estudiar la convergencia casi segura, en probabilidad y en ley de la sucesión anterior.

## Pregunta `r r=r+1; r`.

Sea $\{X_n\}_{n=1}^\infty$ la sucesión de variables aleatorias binomiales de parámetros $n$ y $p_n=\frac{1}{n^2}$. Demostrar, usando la desigualdad de Chebyschev, que la sucesión $\left\{X_n-\frac{1}{n}\right\}_{n=1}^\infty$ converge en probabilidad hacia cero.


# Ley de los grandes números

## Pregunta `r r=r+1; r`.

Sea $\{X_n\}_{n=1}^\infty$ una sucesión de variables aleatorias binomiales de parámetros $m$ y $p$.
1. Demostrar que la sucesión de medias muestrales converge en probabilidad y casi seguramente hacia $mp$.
1. Con ayuda de `R` realizar la simulación correspondiente que comprueba la afirmación anterior. Fijar los valores siguientes $m=10$, $p=\frac{1}{2}$ y $\epsilon =0.05$. Considerar $k=500$ muestras aleatorias de tamaño $N=100$. ¿Qué efecto tienen en las simulaciones anteriores los parámetros $\epsilon$, $p$ y $m$?

## Pregunta `r r=r+1; r`.

Realizar el ejercicio anterior pero en lugar de suponer que las variables $X_n$ son binomiales, suponed que son exponenciales de parámetro $\lambda$. Fijad $\lambda =2$ en la simulación.

# Teorema Central del Límite

## Pregunta `r r=r+1; r`.

El número de accidentes en un trozo de 10 Km de carretera de 2 carriles es una
variable aleatoria de Poisson con media de 2 accidentes por semana. ¿Cuál es
la probabilidad (aproximada) que haya menos de 100 accidentes en este trozo
durante 1 año?

## Pregunta `r r=r+1; r`.

La longitud que se puede estirar un hilo de nilon se modela con una variable aleatoria exponencial
con media de 1524 metros. ¿Cuál es la probabilidad (aproximada) de que la longitud
media de 100 hilos esté entre 1447.8 m y 1691.64 m?

## Pregunta `r r=r+1; r`.Las llamadas telefónicas que se reciben en un conmutador de una industria se producen como
 sucesos de Poisson a razón de 120 por hora. ¿Cuál es la probabilidad que lleguen
entre 110 y 125 llamadas entre las 9.00 y las 10.00 de la mañana un día cualquiera?

## Pregunta `r r=r+1; r`.

La probabilidad de que un jugador de bàsquet enceste es $p$.
¿Cuántos lanzamientos tiene que hacer como mínimo (aproximadamente) para que la probabilidad de
que la media de aciertos esté a distancia 0.01 de $p$ sea de 0.99?

## Pregunta `r r=r+1; r`.

Sea $X_1,\ldots,X_n$ con $n = 48$, una muestra aleatoria simple de una variable
aleatoria uniforme en el intervalo $(0,a)$. Aplicando el Teorema Central del Límite, hallar la probabilidad aproximada de que
$\sum\limits_{i=1}^n X_i >a$.
