---
title: "Probabilidad y variables aleatorias para ML con R y Python"
author: "Ricardo Alberich , Juan Gabriel Gomila y  Arnau Mir"
date: 
output: 
  ioslides_presentation: 
    css: Mery_style.css
    keep_md: yes
    logo: Images/matriz_mov.gif
    widescreen: yes
---

# Probabilidad y variables aleatorias para ML con R y Python

Consulta el curso completo creado por Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir solamente en [Udemy](https://www.udemy.com/course/draft/2521460/?referralCode=E47411C814593EBE3643)

Asienta las bases para convertirte en el Data Scientist del futuro con todo el contenido de estadística descriptiva del curso. En particular verás los mismos contenidos que explicamos en primero de carrera a matemáticos, ingenieros, economistas, biólogos, médicos o informáticos. 

0. [Repaso de Combinatoria](https://joanby.github.io/probabilidad/Tema-0---Prerequisitos)
1. [Probabilidad](https://joanby.github.io/probabilidad/Tema-1---Probabilidad)
2. [Variables aleatorias](https://joanby.github.io/probabilidad/Tema-2---VA)
3. Distribuciones notables (debes desgargar el Rmd para ejecutar los Shiny interactivos)
4. [Complementos avanzados](https://joanby.github.io/probabilidad/Tema-4---Momentos)
5. [Variables bidimensionales](https://joanby.github.io/probabilidad/Tema-5---Varias-Variables)
6. [Variables multidimensionales](https://joanby.github.io/probabilidad/Tema-6---Varias-Variables)
7. [Convergencia y Teorema Central del límite](https://joanby.github.io/probabilidad/Tema-7---TCL)

Y todo con más de 30 horas de vídeo a demanda, cientos de ejercicios, tareas, talleres y trucos de los profesores para que te conviertas en un experto de la materia.
