---
title: "Ejercicios Tema 4 - Complementos de Variables aleatorias"
author: "Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir"
date: "Curso de Probabilidad y Variables Aleatorias con R y Python"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes: \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand\momento{m}
\newcommand{\momentocentral}{\mu}
\newcommand{\FunGenMom}{m}
\newcommand{\FunCar}{\phi}

# Momentos y momentos centrados. Asimetría y apuntamiento.

## Pregunta 1.

 Halla el momento de orden $n$ y el momento centrado de orden $n$ para la variable aleatoria $W$ con función de distribución:
$$
F_W (t)=
\left\{\begin{array}{ll}
0, & \mbox{si $t<3$},
 \\[0.1cm]
\frac13, & \mbox{si $3\leq t<4$},
 \\[0.1cm]
\frac12, & \mbox{si $4\leq t<5$},
 \\[0.1cm] 
\frac23, & \mbox{si $5\leq t<6$},
 \\[0.1cm] 
1, & \mbox{si $t\geq 6$},
\end{array}\right.
$$

### Solución

No es complicado, revisa las clases de teoría si tienes algún problema con alguna definición.

Como es discreta tenemos que 

$$P_W (t)=
\left\{\begin{array}{ll}
\frac26, & \mbox{si $t=3$},
 \\ [0.1cm]
\frac16, & \mbox{si $t=4$},
 \\ [0.1cm] 
\frac16, & \mbox{si $t=5$},
 \\ [0.1cm] 
\frac26, & \mbox{$t=6$},\\
0, & \mbox{en cualquier otro caso}.
\end{array}\right.
$$


El momento respecto al origen de orden $n$ es:

$$
\begin{aligned}
E(W^n)&=\sum_{t=3}^6 t\cdot P(W=t)=
3^n\cdot \frac26+
4^n\cdot  \frac16+
5^n\cdot  \frac16+     
6^n\cdot  \frac26 \\
&=\frac{3^n\cdot 2+4^n\cdot 1+5^n\cdot 1+6^n\cdot 2}{6}=
\frac{3^n\cdot 2+4^n+5^n+6^n \cdot 2}{6}.
\end{aligned}
$$

Para $n=1$ es $E(W)=\frac{27}{6}=\frac{9}{2}=4.5,$ y por lo tanto en momento centrado de orden $n$ es


$$ 
\begin{aligned}
E((W-E(W))^n) &= E((W-4.5)^n) =\sum_{t=3}^6 \left(t-4.5\right)^n\cdot P(W=t) \\ 
&=
\left(3-4.5\right)^n \cdot \frac26+
\left(4-4.5\right)^n \cdot \frac16+
\left(5-4.5\right)^n \cdot  \frac16+     
\left(6-4.5\right)^n \cdot  \frac26 \\ 
&= \frac{(-1.5)^n\cdot 2+(-1)^n\cdot 0.5^n+1\cdot 0.5^n+ 2\cdot 1.5^n}{6}\\
&= \frac{2\cdot (-1^n)\cdot \left(\frac32\right)^n+(-1)^n\cdot \left(\frac12\right)^n+ \left(\frac12\right)^n+
2\cdot \left(\frac32\right)^n}{6}.
\end{aligned}
$$
Finalmente

$$
E((W-E(W))^n)=\left\{\begin{array}{ll}
\frac{-2\cdot \left(\frac32\right)^n-\left(\frac12\right)^n+ \left(\frac12\right)^n+
2\cdot \left(\frac32\right)^n}{6}=0 & \mbox{si } n=1,3,5,7...\mbox{ impar,} \\
\frac{2\cdot \left(\frac32\right)^n+ \left(\frac12\right)^n+ \left(\frac12\right)^n+
2\cdot \left(\frac32\right)^n}{6}=\frac{4\cdot \left(\frac32\right)+2\left(\frac12\right) }{6}=
\frac{2\cdot \left(\frac32\right)^n+\left(\frac12\right)^n }{3}& \mbox{si } n=2,4,6...\mbox{ par}. 
\end{array}
\right.
$$





## Pregunta 2.

Halla el momento de orden $n$ y el momento central de orden $n$ para la variable aleatoria $Z$ con función de probabilidad:
$$f_Z (x)=
\left\{\begin{array}{ll}
{1\over 3}, & \mbox{si $x=0,1,2$},\\ 0, & \mbox{en los otros
casos.}
\end{array}\right.
$$

### Solución

El momento respecto al origen de orden $n$ es:

$$
E(Z^n) =\sum_{x=0}^2 x^n\cdot P(Z=x)=0^n\cdot \frac13+ 1^n\cdot \frac13+2^n \cdot \frac13=\frac{1+2^n}{3}.
$$

La esperanza es del momento respecto al origen para $n=1$ y  es $E(Z)=E(Z^1)=\frac{1+2^1}{3}=1.$

Así el momento central de orden $n$ es 

$$
\begin{aligned}
E((Z-E(Z))^n)& = E((Z-1)^n)=\sum_{x=0}^2 (x-1)^n\cdot P(Z=x)\\
&= (0-1)^n\cdot \frac13+ (1-1)^n\cdot \frac13+(2-1)^n \cdot \frac13\\
&=\frac{(-1)^n+0^n+1^n}{3}=\frac{(-1)^n+1}{3}.
\end{aligned}
$$

Luego 

$$
E((Z-E(Z))^n)= E((Z-1)^n)=
\left\{
\begin{array}{ll}
\frac{(-1)^n+1}{3} =\frac{-1+1}{3}=0, & \mbox{si } n=1,3,5,7...\mbox{ es impar} \\
\frac{(-1)^n+1}{3} =\frac{1+1}{3}=\frac{2}{3}.  & \mbox{si } n=2,4,6...\mbox{par}. 
\end{array}
\right.
$$

## Pregunta 3.

Halla el momento de orden $n$ y el momento central de orden $n$ para la variable aleatoria $X$ con función de densidad:

$$
f(x)=\begin{cases}
1-|x|, & \mbox{si }|x|\leq 1,\\
0, & \mbox{en caso contrario.}
\end{cases}
$$

### Solución

Notemos que 

$$
f(x)=\begin{cases}
1+x, & \mbox{si } -1 \leq x \leq 0,\\
1-x, & \mbox{si } 0 \leq x \leq 1,\\
0, & \mbox{en caso contrario.}
\end{cases}
$$

En este caso el momento de orden $n$  respecto al origen es


$$
\begin{aligned}
E(X^n)&= \int_{-1}^1 x^n  \cdot f(x) dx= \int_{-1}^0 x^n  \cdot (1+x) dx+
\int_{0}^1 x^n  \cdot (1-x) dx\\
& =
\left[\frac{x^{n+1}}{n+1}+\frac{x^{n+2}}{n+2}\right]_{x=-1}^0+
\left[\frac{x^{n+1}}{n+1}-\frac{x^{n+2}}{n+2}\right]_{x=0}^1\\ 
& =
0-\left(\frac{(-1)^{n+1}}{n+1}+\frac{(-1)^{n+2}}{n+2}\right)+
\left(\frac{1^{n+1}}{n+1}-\frac{1^{n+2}}{n+2}\right)-0\\ & =
\left(\frac{(-1)^{n+2}}{n+1}+\frac{(-1)^{n+3}}{n+2}\right)+
\left(\frac{1}{n+1}-\frac{1}{n+2}\right)\\ & =
(-1)^{n+2}\cdot \left(\frac{1}{n+1}-\frac{1}{n+2}\right)+
\left(\frac{1}{n+1}-\frac{1}{n+2}\right)=
\\ & =
(-1)^{n+2}\cdot \left(\frac{(n+2)-(n+1)}{(n+1)\cdot (n+2)}\right)+
\left(\frac{n+2-(n+1)}{(n+1)\cdot (n+2)}\right)\\
& =
\left((-1)^{n+2}+1\right)\cdot\left(\frac{1}{(n+1)\cdot(n+2)}\right) \\ & = 
\left\{
\begin{array}{rl}
0, & \mbox{si } n=1,3,5,7... \mbox{ es impar} \\
\frac{2}{(n+1)\cdot(n+2)},  & \mbox{si } n=2,4,6...\mbox{ es par}. 
\end{array}
\right.
\end{aligned}
$$
Así que la esperanza vale $E(X)=0$.


Luego el momento respecto a la media de orden $n$ es igual  al momento del mismo orden respecto al origen:

$$E((X-E(X))^n)=E(X^n)= 
\left\{
\begin{array}{ll}
0, & \mbox{si } n=1,3,5,7... \mbox{ es impar} \\
\frac{2}{(n+1)\cdot(n+2)}.  & \mbox{si } n=2,4,6...\mbox{ es par}. 
\end{array}
\right.
$$


## Pregunta 4.

Halla el momento de orden $n$ y el momento central de orden $n$ para la variable aleatoria $Y$ con función de distribución:

$$
F_Y(t)=
\left\{\begin{array}{ll}
0, & \mbox{si $t<0$},\\
\sqrt{t}, & \mbox{si $0\leq t\leq 1$},\\ 1, &
\mbox{si $t>1$},
\end{array}\right.
$$

### Solución

Ante todo  la densidad  es $f_y(t)==

$$
\left\{\begin{array}{ll}
0, & \mbox{si $t<0$},\\
\frac{1}{2} \cdot {t}^{-\frac12}, 
& \mbox{si $0\leq t\leq 1$},\\ 0, &
\mbox{en otro caso},
\end{array}\right.
$$


$$
\begin{aligned}
E(X^n)&= \int_0^1 t^n \cdot \frac{1}{2} t^{\frac{-1}{2}} \cdot dt=
\frac12\cdot \int_0^1 t^{n-\frac{1}{2}} \cdot dt=
\frac12\cdot \left[\frac{t^{n-\frac{1}{2}+1}}{n-\frac{1}{2}+1}\right]_{t=0}^1\\ & = 
\frac12\cdot \left[\frac{t^{n+\frac12}}{n+\frac12}\right]_{t=0}^1= \frac{1}{2\cdot n+1}.
\end{aligned}
$$



El valor esperado es $E(X)=\frac{1}{1+\frac12}=\frac13.$

Así que el momento central de orden $n$ es 

$$
\begin{aligned}
E\left(\left(X-\frac13\right)^n\right) &=
\int_0^1 \left(t-\frac13\right)^n \cdot \frac12 \cdot t^{-\frac12}\cdot dt =
\frac12\cdot \int_0^1 \sum_{k=0}^n \binom{n}{k} \cdot t^{n-k}\cdot
\left(-\frac13\right)^k \cdot t^{-\frac12} dt \\ & =
\frac12\cdot \sum_{k=0}^n \binom{n}{k}\cdot \left(-\frac{1}{3}\right)^k\cdot  \int_0^1  t^{n-k-\frac12}\cdot dt \\ & =
\frac12\cdot\sum_{k=0}^n \binom{n}{k} \cdot \left(-\frac{1}{3}\right)^k\cdot 
\left[\frac{t^{n-k-\frac12+1}}{n-k-\frac12+1} \right]_{t=0}^1 \\ & =  
\frac12\cdot\sum_{k=0}^n \binom{n}{k}\cdot \left(-\frac{1}{3}\right)^k\cdot 
\frac{1^{n-k+\frac32}}{n-k+\frac12}-0\\ & =
\frac12\cdot\sum_{k=0}^n \binom{n}{k}\cdot \left(-\frac{1}{3}\right)^k\cdot 
\frac{1}{n-k+\frac12}.
\end{aligned}
$$



